import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { TokenValue } from './load.js';
import { tokenPathToCssVar } from './resolve.js';

/**
 * Global CSS reset (box-sizing)
 */
const GLOBAL_RESET = `/* Global reset - box-sizing */
*,
*::before,
*::after {
  box-sizing: border-box;
}
`;

/**
 * Generate CSS custom properties file
 */
export function emitCss(
  tokens: Map<string, TokenValue>,
  outputPath: string,
  selector: string = ':root'
): void {
  const lines: string[] = [
    '/* Auto-generated by build-tokens.ts - DO NOT EDIT */',
    '',
  ];

  // Add global reset only for base CSS (not theme overrides)
  if (selector === ':root') {
    lines.push(GLOBAL_RESET);
  }

  lines.push(`${selector} {`);

  for (const [path, token] of tokens) {
    const varName = tokenPathToCssVar(path);
    const comment = token.description ? ` /* ${token.description} */` : '';
    lines.push(`  --${varName}: ${token.value};${comment}`);
  }

  lines.push('}');
  lines.push('');

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, lines.join('\n'));
  console.log(`Generated: ${outputPath}`);
}

/**
 * Generate theme-specific CSS file
 */
export function emitThemeCss(
  tokens: Map<string, TokenValue>,
  themeName: string,
  outputPath: string
): void {
  const selector = `[data-theme="${themeName}"]`;
  emitCss(tokens, outputPath, selector);
}

/**
 * Generate base tokens CSS (default theme values)
 */
export function emitBaseCss(
  tokens: Map<string, TokenValue>,
  outputPath: string
): void {
  emitCss(tokens, outputPath, ':root');
}
