import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { TokenValue } from './load.js';
import { tokenPathToCssVar } from './resolve.js';

/**
 * Generate SCSS variables that reference CSS custom properties
 * This keeps SCSS theme-agnostic
 */
export function emitScss(
  tokens: Map<string, TokenValue>,
  outputPath: string
): void {
  const lines: string[] = [
    '// Auto-generated by build-tokens.ts - DO NOT EDIT',
    '// These SCSS variables reference CSS custom properties for runtime theming',
    '',
  ];

  // Group tokens by category for organization
  const categories = new Map<string, Map<string, TokenValue>>();

  for (const [path, token] of tokens) {
    const category = path.split('.')[0];
    if (!categories.has(category)) {
      categories.set(category, new Map());
    }
    categories.get(category)!.set(path, token);
  }

  for (const [category, categoryTokens] of categories) {
    lines.push(`// ${category.charAt(0).toUpperCase() + category.slice(1)}`);

    for (const [path, token] of categoryTokens) {
      const varName = tokenPathToCssVar(path);
      const scssVarName = `$${varName}`;
      const comment = token.description ? ` // ${token.description}` : '';
      lines.push(`${scssVarName}: var(--${varName});${comment}`);
    }

    lines.push('');
  }

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, lines.join('\n'));
  console.log(`Generated: ${outputPath}`);
}
