import { writeFileSync, mkdirSync } from 'fs';
import { dirname } from 'path';
import { TokenValue } from './load.js';
import { tokenPathToCssVar } from './resolve.js';

/**
 * Generate TypeScript exports for type-safe token access
 */
export function emitTs(
  tokens: Map<string, TokenValue>,
  outputPath: string
): void {
  const varNames = Array.from(tokens.keys()).map(tokenPathToCssVar);

  const lines: string[] = [
    '// Auto-generated by build-tokens.ts - DO NOT EDIT',
    '',
    '/**',
    ' * All available design token names',
    ' */',
    'export const tokenNames = [',
    ...varNames.map(name => `  '${name}',`),
    '] as const;',
    '',
    '/**',
    ' * Union type of all token names',
    ' */',
    'export type TokenName = typeof tokenNames[number];',
    '',
    '/**',
    ' * Get a CSS variable reference for a token',
    ' * @example cssVar("surface-canvas") // returns "var(--surface-canvas)"',
    ' */',
    'export function cssVar(name: TokenName): string {',
    '  return `var(--${name})`;',
    '}',
    '',
    '/**',
    ' * Token categories for organization',
    ' */',
    'export const tokenCategories = {',
  ];

  // Group by category
  const categories = new Map<string, string[]>();
  for (const [path] of tokens) {
    const category = path.split('.')[0];
    if (!categories.has(category)) {
      categories.set(category, []);
    }
    categories.get(category)!.push(tokenPathToCssVar(path));
  }

  for (const [category, names] of categories) {
    lines.push(`  ${category}: [${names.map(n => `'${n}'`).join(', ')}] as const,`);
  }

  lines.push('} as const;');
  lines.push('');

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, lines.join('\n'));
  console.log(`Generated: ${outputPath}`);
}
